# Generated by Django 3.2.5 on 2021-11-10 16:54

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=200)),
                ('name_id', models.CharField(max_length=200)),
                ('old_handle', jsonfield.fields.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
